
-- 6) erp_inventory
CREATE TABLE tb_mgmt.erp_inventory (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id           UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  product_code        TEXT UNIQUE,
  erp_inventory_name  TEXT   NOT NULL UNIQUE,
  inventory_unit_id   BIGINT,
  created_at          TIMESTAMP DEFAULT NOW(),
  updated_at          TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_erp_inventory_unit
    FOREIGN KEY (inventory_unit_id) REFERENCES tb_mgmt.units(id)
);
