

-- 10) erp_inventory_suppliers
CREATE TABLE tb_mgmt.erp_inventory_suppliers (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id             UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  erp_inventory_id      BIGINT NOT NULL UNIQUE,
  supplier_id           BIGINT NOT NULL,
  supplier_product_name TEXT   NOT NULL UNIQUE,
  created_at            TIMESTAMP DEFAULT NOW(),
  updated_at            TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_eis_inventory
    FOREIGN KEY (erp_inventory_id) REFERENCES tb_mgmt.erp_inventory(id),
  CONSTRAINT fk_eis_supplier
    FOREIGN KEY (supplier_id) REFERENCES tb_mgmt.suppliers(id)
);
