
-- 5) erp_customers
CREATE TABLE tb_mgmt.erp_customers (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id         UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  erp_customer_name TEXT   NOT NULL UNIQUE,
  created_at        TIMESTAMP DEFAULT NOW(),
  updated_at        TIMESTAMP DEFAULT NOW()
);
