
-- 7) ingredients
CREATE TABLE tb_mgmt.ingredients (
  id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id                 UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  ingredient_name           TEXT    NOT NULL,
  is_semi_product           BOOLEAN NOT NULL,
  purchase_source           TEXT,
  erp_inventory_product_code TEXT,
  created_at                TIMESTAMP DEFAULT NOW(),
  updated_at                TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_ingredients_erp_product_code
    FOREIGN KEY (erp_inventory_product_code) REFERENCES tb_mgmt.erp_inventory(product_code)
);