

-- 9) pos_items
CREATE TABLE tb_mgmt.pos_items (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id        UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  pos_item_name    TEXT   NOT NULL,
  pos_option_group TEXT,
  pos_option_name  TEXT,
  status           TEXT   NOT NULL,
  created_at       TIMESTAMP DEFAULT NOW(),
  updated_at       TIMESTAMP DEFAULT NOW()
);