
-- 13) pos_item_mapping
CREATE TABLE tb_mgmt.pos_item_mapping (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id   UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  pos_item_id BIGINT NOT NULL,
  product_id  BIGINT NOT NULL,
  created_at  TIMESTAMP DEFAULT NOW(),
  updated_at  TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_pim_pos_item
    FOREIGN KEY (pos_item_id) REFERENCES tb_mgmt.pos_items(id),
  CONSTRAINT fk_pim_product
    FOREIGN KEY (product_id) REFERENCES tb_mgmt.products(id)
);
