
-- 4) pos_stores
CREATE TABLE tb_mgmt.pos_stores (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id     UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  pos_store_name TEXT  NOT NULL UNIQUE,
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW()
);
