

-- 8) products
CREATE TABLE tb_mgmt.products (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id    UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  product_name TEXT   NOT NULL UNIQUE,
  category_id  BIGINT,
  created_at   TIMESTAMP DEFAULT NOW(),
  updated_at   TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_products_category
    FOREIGN KEY (category_id) REFERENCES tb_mgmt.product_categories(id)
);