
-- 1) product_categories
CREATE TABLE tb_mgmt.product_categories (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id     UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  category_name TEXT   NOT NULL UNIQUE,
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW()
);
