
-- 12) semi_product_bom
CREATE TABLE tb_mgmt.semi_product_bom (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id        UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  semi_product_id  BIGINT NOT NULL,
  ingredient_id    BIGINT NOT NULL UNIQUE,
  quantity         NUMERIC NOT NULL UNIQUE,
  unit_id          BIGINT NOT NULL,
  created_at       TIMESTAMP DEFAULT NOW(),
  updated_at       TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_spb_semi_product
    FOREIGN KEY (semi_product_id) REFERENCES tb_mgmt.ingredients(id),
  CONSTRAINT fk_spb_ingredient
    FOREIGN KEY (ingredient_id) REFERENCES tb_mgmt.ingredients(id),
  CONSTRAINT fk_spb_unit
    FOREIGN KEY (unit_id) REFERENCES tb_mgmt.units(id)
);
