
-- 3) suppliers
CREATE TABLE tb_mgmt.suppliers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id     UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  supplier_name TEXT   NOT NULL UNIQUE,
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW()
);
