
-- 14) unit_conversions
CREATE TABLE tb_mgmt.unit_conversions (
  id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id                  UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  erp_inventory_id           BIGINT NOT NULL UNIQUE,
  warehouse_in_unit_id       BIGINT,
  warehouse_in_quantity      NUMERIC,
  warehouse_in_base_unit_id  BIGINT,
  warehouse_out_unit_id      BIGINT,
  warehouse_out_quantity     NUMERIC,
  warehouse_out_base_unit_id BIGINT,
  created_at                 TIMESTAMP DEFAULT NOW(),
  updated_at                 TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_uc_inventory
    FOREIGN KEY (erp_inventory_id) REFERENCES tb_mgmt.erp_inventory(id),
  CONSTRAINT fk_uc_in_unit
    FOREIGN KEY (warehouse_in_unit_id) REFERENCES tb_mgmt.units(id),
  CONSTRAINT fk_uc_in_base_unit
    FOREIGN KEY (warehouse_in_base_unit_id) REFERENCES tb_mgmt.units(id),
  CONSTRAINT fk_uc_out_unit
    FOREIGN KEY (warehouse_out_unit_id) REFERENCES tb_mgmt.units(id),
  CONSTRAINT fk_uc_out_base_unit
    FOREIGN KEY (warehouse_out_base_unit_id) REFERENCES tb_mgmt.units(id)
);