
-- 2) units
CREATE TABLE tb_mgmt.units (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id  UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  unit_name  TEXT   NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
