
-- 7) ingredients (bom materials)
CREATE TABLE tb_mgmt.ingredients (
  id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id                 UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  ingredient_name           TEXT    NOT NULL,
  is_semi_product           BOOLEAN NOT NULL,
  purchase_source           TEXT,
  erp_inventory_id           BIGINT,
  created_at                TIMESTAMP DEFAULT NOW(),
  updated_at                TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_ingredients_erp_inventory_id
    FOREIGN KEY (erp_inventory_id) REFERENCES tb_mgmt.erp_inventory(id)
);