
-- inventory_details
-- 用於保存 ERP 庫存品項的補貨/效期等參數。

create table tb_mgmt.inventory_details (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
	erp_inventory_id BIGINT NOT NULL UNIQUE, -- 對應 erp_inventory.id
	category text,                  -- 類別（例如：長效*熱銷）
	rank integer,                   -- 排行
	shelf_life_days integer,        -- 效期（天）
	shelf_life_category text,       -- 效期分類（例如：長效* / 中效*）
	sales_grade text,              -- 銷度（例如：熱銷）
	lead_time_days integer,         -- 交期（天）
	delivery text,                 -- 配送（文字描述）
	max_purchase_param numeric,     -- 最大進貨量參數
	safety_stock_param numeric,     -- 安全庫存參數
	inventory_turnover_days numeric, -- 庫存週轉天數
	created_at TIMESTAMP DEFAULT NOW(),
	updated_at TIMESTAMP DEFAULT NOW(),
	CONSTRAINT fk_inventory_details_erp_inventory
		FOREIGN KEY (erp_inventory_id) REFERENCES tb_mgmt.erp_inventory(id)
);

