

-- 9) pos_items
CREATE TABLE tb_mgmt.pos_items (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id        UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  pos_item_name    TEXT   NOT NULL,
  pos_option_group_id BIGINT,
  pos_option_value_id BIGINT,
  status_id        BIGINT NOT NULL,
  created_at       TIMESTAMP DEFAULT NOW(),
  updated_at       TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_pos_items_option_group
    FOREIGN KEY (pos_option_group_id) REFERENCES tb_mgmt.pos_option_group(id),
  CONSTRAINT fk_pos_items_option_value
    FOREIGN KEY (pos_option_value_id) REFERENCES tb_mgmt.pos_option_value(id),
  CONSTRAINT fk_pos_items_status
    FOREIGN KEY (status_id) REFERENCES tb_mgmt.status(id)
);