
-- 18) pos_option_value
-- pos_items.pos_option_name 的 master table
CREATE TABLE tb_mgmt.pos_option_value (
	id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	public_id           UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
	pos_option_value TEXT NOT NULL UNIQUE,
	created_at          TIMESTAMP DEFAULT NOW(),
	updated_at          TIMESTAMP DEFAULT NOW()
);

