
-- 16) pos_option_group
-- pos_items.pos_option_group 的 master table（僅存選項群組本身）
CREATE TABLE tb_mgmt.pos_option_group (
	id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	public_id             UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
	pos_option_group TEXT   NOT NULL UNIQUE,
	created_at            TIMESTAMP DEFAULT NOW(),
	updated_at            TIMESTAMP DEFAULT NOW()
);

