
-- 11) product_bom
CREATE TABLE tb_mgmt.product_bom (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id     UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  product_id    BIGINT NOT NULL,
  ingredient_id BIGINT,
  quantity      NUMERIC NOT NULL,
  unit_id       BIGINT NOT NULL,
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_product_bom_product
    FOREIGN KEY (product_id) REFERENCES tb_mgmt.products(id),
  CONSTRAINT fk_product_bom_ingredient
    FOREIGN KEY (ingredient_id) REFERENCES tb_mgmt.ingredients(id),
  CONSTRAINT fk_product_bom_unit
    FOREIGN KEY (unit_id) REFERENCES tb_mgmt.units(id)
);
