
-- 17) status
-- 通用狀態 master table（例如：有效/無效）
CREATE TABLE tb_mgmt.status (
	id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	public_id   UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
	status TEXT   NOT NULL UNIQUE,
	created_at  TIMESTAMP DEFAULT NOW(),
	updated_at  TIMESTAMP DEFAULT NOW()
);

