

-- 15) stores
CREATE TABLE tb_mgmt.stores (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id        UUID   NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  pos_store_name   BIGINT UNIQUE,
  erp_customer_name BIGINT NOT NULL UNIQUE,
  address_zh       TEXT,
  address_en       TEXT,
  country          TEXT,
  city             TEXT,
  district         TEXT,
  latitude         NUMERIC,
  longitude        NUMERIC,
  status           TEXT   NOT NULL,
  store_type       TEXT   NOT NULL,
  created_at       TIMESTAMP DEFAULT NOW(),
  updated_at       TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_stores_pos_store
    FOREIGN KEY (pos_store_name) REFERENCES tb_mgmt.pos_stores(id),
  CONSTRAINT fk_stores_erp_customer
    FOREIGN KEY (erp_customer_name) REFERENCES tb_mgmt.erp_customers(id)
);
