GRANT USAGE ON SCHEMA tb_mgmt TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA tb_mgmt TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tb_mgmt TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA tb_mgmt GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA tb_mgmt GRANT ALL ON SEQUENCES TO service_role;
