-- Insert / upsert unit conversions (generated from 工作表24.csv)
-- Note: rows whose erp_inventory_name is not found in tb_mgmt.erp_inventory will be skipped;
--       a list of missing names will be returned at the end for review.

WITH input AS (
  SELECT *
  FROM (VALUES
    ('◎漢堡肉', '盤', 20.0, '粒', '捆', 15.0, '盤'),
    ('◎豬排肉', '盤', 20.0, '片', '捆', 20.0, '盤'),
    ('◎大火腿', '條', 28.0, '片', '籃', 5.0, '條'),
    ('◎小火腿', '條', 98.0, '片', '籃', 8.0, '條'),
    ('◎熱狗', '包', 50.0, '條', '箱', 24.0, '包'),
    ('◎特調德式香腸', '包', 19.0, '條', '箱', 12.0, '包'),
    ('◎低脂培根', '包', 19.0, '片', '籃', 40.0, '包'),
    ('◎雞塊', '包', 42.0, '塊', '箱', 10.0, '包'),
    ('◎燻雞肉片', '包', 990.0, 'g', '箱', 12.0, '包'),
    ('◎卡啦雞腿', '包', 10.0, '片', '箱', 6.0, '包'),
    ('◎手工蛋餅皮', '包', 30.0, '片', '箱', 12.0, '包'),
    ('◎冷凍蘿蔔糕', '包', 10.0, '片', '箱', 11.0, '包'),
    ('◎黑胡椒鐵板麵', '箱', 24.0, '包', '箱', 1.0, '箱'),
    ('◎蕃茄雞肉麵', '箱', 24.0, '包', '箱', 1.0, '箱'),
    ('◎好吃堡', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎美式貝果', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎樂活堡', '個', 1.0, '個', '籃', 120.0, '個'),
    ('◎潛艇堡', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎豆漿(HB)', '包', 1000.0, 'g', '箱', 10.0, '包'),
    ('◎特選薏仁漿', '包', 1000.0, 'g', '箱', 10.0, '包'),
    ('◎美式薯條', '包', 2000.0, 'g', '箱', 6.0, '包'),
    ('◎牛肉堡(10片)', '包', 10.0, '片', '箱', 6.0, '包'),
    ('◎蕃茄湯底(1KG)-MS', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎牛奶湯底-MS', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎蕃茄吐司-F', '條', 20.0, '片', '籃', 5.0, '條'),
    ('◎咕穀堡-F', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎紫米堡', '箱', 30.0, '個', '箱', 1.0, '箱'),
    ('◎冷凍青花菜-S', '包', 1000.0, 'g', '箱', 10.0, '包'),
    ('◎雞高湯', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎丹麥吐司', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎義大利麵', '箱', 35.0, '包', '箱', 1.0, '箱'),
    ('◎無糖豆漿', '包', 1500.0, 'g', '箱', 6.0, '包'),
    ('◎蘑菇炒料', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎美式鬆餅-HT', '箱', 30.0, '包', '箱', 1.0, '箱'),
    ('◎麥香雞肉堡(通)', '箱', 50.0, '片', '箱', 1.0, '箱'),
    ('◎蕃茄烏龍麵', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎蕃茄厚片吐司', '條', 12.0, '片', '籃', 5.0, '條'),
    ('◎藜麥米板', '箱', 60.0, '片', '箱', 1.0, '箱'),
    ('◎日式牛丼', '包', 1000.0, 'g', '箱', 20.0, '包'),
    ('◎四角薯餅', '條', 20.0, '片', '箱', 12.0, '條'),
    ('◎冷凍水滴薯球', '包', 155.0, '顆', '箱', 4.0, '包'),
    ('◎奶青醬', '箱', 35.0, '包', '箱', 1.0, '箱'),
    ('◎粉紅香頌麵包', NULL, NULL, NULL, NULL, NULL, NULL),
    ('◎牛奶土司', '條', 20.0, '片', '籃', 5.0, '條'),
    ('◎冷凍可口芋簽糕', '包', 6.0, '份', '箱', 6.0, '包'),
    ('◎起司豬排', '包', 10.0, '片', '箱', 12.0, '包'),
    ('◎培根白醬', '包', 1.0, '包', '箱', 50.0, '包'),
    ('◎黃金蝦仁', '包', 1.0, '公斤', '箱', 10.0, '包'),
    ('◎好事堡(新)', '包', 20.0, '個', '箱', 2.0, '包'),
    ('◎原味船型薯條', '包', 2270.0, 'g', '箱', 6.0, '包'),
    ('◎舒肥香草雞胸肉', '片', 100.0, 'g', '箱', 50.0, '片'),
    ('◎切塊紅皮熟栗地瓜', '包', 1000.0, 'g', '箱', 12.0, '包'),
    ('◎魷魚花枝排', '盒', 18.0, '片', '箱', 8.0, '盒'),
    ('◎巧達玉米濃湯', '包', 500.0, 'g', '箱', 20.0, '包'),
    ('●奶精', '罐', 450.0, 'g', '籃', 30.0, '罐'),
    ('●千島醬', '包', 500.0, 'g', '箱', 20.0, '包'),
    ('●紐約客燒醬', '包', 500.0, 'g', '箱', 30.0, '包'),
    ('●蕃茄村起士片(84片)', '條', 84.0, '片', '箱', 8.0, '條'),
    ('●超拉絲乳酪絲', '包', 1000.0, 'g', '箱', 10.0, '包'),
    ('●荷蘭醬', '包', 500.0, 'g', '箱', 40.0, '包'),
    ('◎龍蝦沙拉(凍)', '包', 500.0, 'g', '箱', 20.0, '包'),
    ('●櫻島家100%鮮奶', '瓶', 936.0, 'ml', '籃', 16.0, '瓶'),
    ('●韓式泡菜(3KG)', '罐', 3000.0, 'g', '籃', 5.0, '罐'),
    ('●韓式泡菜(600g)', '罐', 600.0, 'g', '箱', 15.0, '罐'),
    ('特選芝麻肉鬆', '罐', 1800.0, 'g', '箱', 12.0, '罐'),
    ('特選紅茶24入', NULL, NULL, NULL, NULL, NULL, NULL),
    ('檸檬紅茶', NULL, NULL, NULL, NULL, NULL, NULL),
    ('水蜜桃可爾必思', '罐', 1500.0, 'g', '箱', 6.0, '罐'),
    ('鮮肉柳丁汁', NULL, NULL, NULL, NULL, NULL, NULL),
    ('焦糖糖漿', '罐', 980.0, 'g', '箱', 12.0, '罐'),
    ('IN沙拉醬', '盒', 3000.0, 'g', '箱', 6.0, '盒'),
    ('●墨西哥醬', NULL, NULL, NULL, NULL, NULL, NULL),
    ('※芒果沙拉', '包', 500.0, 'g', '箱', 20.0, '包'),
    ('※雞塊沾醬', '包', 500.0, 'g', '箱', 20.0, '包'),
    ('※芥末醬', '包', 500.0, 'g', '箱', 20.0, '包'),
    ('※特選田園沙拉', '包', 500.0, 'g', '箱', 20.0, '包'),
    ('蕃茄醬', '罐', 3200.0, 'g', '箱', 6.0, '罐'),
    ('蒜味醬油', '罐', 1600.0, 'g', '箱', 6.0, '罐'),
    ('玉米粒', '箱', 8160.0, 'g', '箱', 1.0, '箱'),
    ('花生醬', '罐', 3000.0, 'g', '箱', 6.0, '罐'),
    ('草莓醬', '罐', 3000.0, 'g', '箱', 6.0, '罐'),
    ('巧克力醬', '罐', 3000.0, 'g', '箱', 6.0, '罐'),
    ('奶酥醬', '罐', 1800.0, 'g', '箱', 6.0, '罐'),
    ('紅茶DJ-(蕃)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('蘋果醋', '桶', 2000.0, 'g', '箱', 6.0, '桶'),
    ('皇家特選咖啡豆', '包', 454.0, 'g', '箱', 20.0, '包'),
    ('福曼沙香韻紅茶', '包', 600.0, 'g', '箱', 30.0, '包'),
    ('全脂牛奶(箱)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('琥珀糖漿(箱)', '箱', 24000.0, 'g', '箱', 1.0, '箱'),
    ('梅醬', '袋', 500.0, 'g', '袋', 1.0, '袋'),
    ('櫻島家-巧克力保久乳', NULL, NULL, NULL, NULL, NULL, NULL),
    ('櫻島家-蘋果保久乳', NULL, NULL, NULL, NULL, NULL, NULL),
    ('櫻島家-麥芽保久乳', NULL, NULL, NULL, NULL, NULL, NULL),
    ('櫻島家-草莓保久乳', '箱', 24.0, '瓶', '箱', 1.0, '箱'),
    ('櫻島家-原味保久乳', NULL, NULL, NULL, NULL, NULL, NULL),
    ('椒麻醬', '袋', 100.0, '包', '袋', 1.0, '袋'),
    ('瓜地馬拉咖啡豆', NULL, NULL, NULL, NULL, NULL, NULL),
    ('榛果果露', '罐', 1000.0, 'g', '箱', 6.0, '罐'),
    ('大海鮪魚', '箱', 3720.0, 'g', '箱', 1.0, '箱'),
    ('阿華田1KG', '包', 1000.0, 'g', '箱', 12.0, '包'),
    ('蕃茄醬包10g(袋)', '袋', 2000.0, '包', '箱', 5.0, '袋'),
    ('醬油膏10g(袋)', '袋', 2000.0, 'g', '箱', 5.0, '袋'),
    ('丼飯醬', '罐', 1800.0, 'g', '箱', 6.0, '罐'),
    ('韓國辣味粉', '包', 500.0, 'g', '箱', 10.0, '包'),
    ('蕃茄村村拌麵', '箱', 30.0, '包', '箱', 1.0, '箱'),
    ('Q彈鍋燒意麵', '箱', 42.0, '包', '箱', 1.0, '箱'),
    ('醬香風味醬', '袋', 250.0, '包', '袋', 1.0, '袋'),
    ('酸黃瓜', '罐', 1400.0, 'g', '箱', 6.0, '罐'),
    ('韓國柚子醬', '罐', 2000.0, 'g', '箱', 6.0, '罐'),
    ('水果叉', '盒', 1.0, '盒', '箱', 50.0, '盒'),
    ('湯匙', '包', 1.0, '支', '箱', 24.0, '包'),
    ('面紙', NULL, NULL, NULL, NULL, NULL, NULL),
    ('橡皮筋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('50斤大垃圾袋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('生菜沙拉盒蓋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('套餐用餐叉', '包', 100.0, '根', '箱', 50.0, '包'),
    ('大茶匙', NULL, NULL, NULL, NULL, NULL, NULL),
    ('午餐外帶盒', NULL, NULL, NULL, NULL, NULL, NULL),
    ('潛艇外帶盒(55個)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('隔熱杯套(25個)', '束', 25.0, '個', '箱', 40.0, '束'),
    ('長方鋁盒蓋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('1000C.C湯杯', '條', 1.0, '個', '箱', 12.0, '條'),
    ('1000C.C杯蓋', '條', 1.0, '條', '箱', 12.0, '條'),
    ('玉米湯杯蓋', '條', 50.0, '個', '箱', 20.0, '條'),
    ('咖啡耐熱杯蓋', '條', 50.0, '張', '箱', 20.0, '條'),
    ('902凸蓋', '條', 50.0, '個', '箱', 12.0, '條'),
    ('902扁碗', '條', 50.0, '個', '箱', 12.0, '條'),
    ('25cm斜口吸管', '包', 500.0, '根', '箱', 10.0, '包'),
    ('450C.C.紙湯杯', NULL, NULL, NULL, NULL, NULL, NULL),
    ('450C.C.湯杯蓋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('漢堡盒蓋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('漢堡盒', NULL, NULL, NULL, NULL, NULL, NULL),
    ('S號吐司盒', NULL, NULL, NULL, NULL, NULL, NULL),
    ('山形吐司塑膠膜', NULL, NULL, NULL, NULL, NULL, NULL),
    ('90杯蓋(U型孔)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('90冷飲蓋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('22公分粗吸管', NULL, NULL, NULL, NULL, NULL, NULL),
    ('4杯袋(透明)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('六兩防油紙袋(空白)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('90四杯架', NULL, NULL, NULL, NULL, NULL, NULL),
    ('四杯架(透明)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('免洗筷(空白版)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('立頓隨身瓶', NULL, NULL, NULL, NULL, NULL, NULL),
    ('750ML黑色通用盒', NULL, NULL, NULL, NULL, NULL, NULL),
    ('750ML透明通用盒蓋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('8吋三格餐盒', '條', 50.0, '個', '箱', 6.0, '條'),
    ('8吋三格餐盒蓋', '條', 50.0, '個', '箱', 6.0, '條'),
    ('2oz醬料杯', '個', 1.0, '個', '條', 125.0, '個'),
    ('2oz醬料杯蓋', '條', 125.0, '個', '箱', 20.0, '條'),
    ('湯碗蓋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('玉米湯杯(蕃)', '條', 50.0, '個', '箱', 20.0, '條'),
    ('大冰杯(蕃)', '入', 1.0, '個', '箱', 1000.0, '入'),
    ('中冰杯(蕃)', '條', 50.0, '個', '箱', 20.0, '條'),
    ('400咖啡杯(蕃)', '條', 50.0, '個', '箱', 20.0, '條'),
    ('冰淇淋杯(50個)(蕃)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('土司盒(蕃)', '條', 100.0, '個', '箱', 6.0, '條'),
    ('點心盒(蕃)', '條', 100.0, '個', '箱', 10.0, '條'),
    ('三明治袋(蕃)', '包', 100.0, '個', '箱', 100.0, '包'),
    ('L型漢堡袋(蕃)', '束', 200.0, '個', '箱', 30.0, '束'),
    ('套袋吸管(蕃)', '包', 500.0, '根', '箱', 10.0, '包'),
    ('封口膜(蕃)', '捲', 3000.0, '張', '箱', 6.0, '捲'),
    ('五號包裝袋(蕃)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('卡啦燻雞雞塊共用包袋(蕃)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('熱狗袋(蕃)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('玉米湯杯(公)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('咖啡豆鋁箔袋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('蕃茄村蛋餅袋', '箱', 2000.0, '入', '箱', 1.0, '箱'),
    ('三號包裝袋(袋)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('四號包裝袋(袋)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('牛皮抱袋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('熱狗包裝袋(蕃)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('12oz(牛皮)咖啡杯', NULL, NULL, NULL, NULL, NULL, NULL),
    ('C90H透明咖啡杯蓋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('700cc杯(蕃)', '個', 1.0, '個', '箱', 1000.0, '個'),
    ('500咖啡杯(蕃)', NULL, NULL, NULL, NULL, NULL, NULL),
    ('蕃茄村牛仔制服-M', '包', 5.0, '入', '箱', 100.0, '件'),
    ('蕃茄村牛仔制服-XL', NULL, NULL, NULL, NULL, NULL, NULL),
    ('蕃茄村2018手提環保袋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('5入咖啡盒', NULL, NULL, NULL, NULL, NULL, NULL),
    ('咖啡禮盒紙袋', NULL, NULL, NULL, NULL, NULL, NULL),
    ('北北卡藝妓五盒組', NULL, NULL, NULL, NULL, NULL, NULL),
    ('360冷熱杯', '箱', 1000.0, '入', '箱', 1.0, '箱')
  ) AS v(
    erp_inventory_name,
    warehouse_in_unit,
    warehouse_in_quantity,
    warehouse_in_base_unit,
    warehouse_out_unit,
    warehouse_out_quantity,
    warehouse_out_base_unit
  )
),
joined AS (
  SELECT
    i.*,
    ei.id AS erp_inventory_id,
    u_in.id AS warehouse_in_unit_id,
    u_in_base.id AS warehouse_in_base_unit_id,
    u_out.id AS warehouse_out_unit_id,
    u_out_base.id AS warehouse_out_base_unit_id
  FROM input i
  LEFT JOIN tb_mgmt.erp_inventory ei
    ON ei.erp_inventory_name = i.erp_inventory_name
  LEFT JOIN tb_mgmt.units u_in
    ON u_in.unit_name = i.warehouse_in_unit
  LEFT JOIN tb_mgmt.units u_in_base
    ON u_in_base.unit_name = i.warehouse_in_base_unit
  LEFT JOIN tb_mgmt.units u_out
    ON u_out.unit_name = i.warehouse_out_unit
  LEFT JOIN tb_mgmt.units u_out_base
    ON u_out_base.unit_name = i.warehouse_out_base_unit
),
to_upsert AS (
  SELECT
    erp_inventory_id,
    warehouse_in_unit_id,
    warehouse_in_quantity,
    warehouse_in_base_unit_id,
    warehouse_out_unit_id,
    warehouse_out_quantity,
    warehouse_out_base_unit_id
  FROM joined
  WHERE erp_inventory_id IS NOT NULL
)
INSERT INTO tb_mgmt.unit_conversions (
  erp_inventory_id,
  warehouse_in_unit_id,
  warehouse_in_quantity,
  warehouse_in_base_unit_id,
  warehouse_out_unit_id,
  warehouse_out_quantity,
  warehouse_out_base_unit_id
)
SELECT
  erp_inventory_id,
  warehouse_in_unit_id,
  warehouse_in_quantity,
  warehouse_in_base_unit_id,
  warehouse_out_unit_id,
  warehouse_out_quantity,
  warehouse_out_base_unit_id
FROM to_upsert
ON CONFLICT (erp_inventory_id) DO UPDATE SET
  warehouse_in_unit_id       = EXCLUDED.warehouse_in_unit_id,
  warehouse_in_quantity      = EXCLUDED.warehouse_in_quantity,
  warehouse_in_base_unit_id  = EXCLUDED.warehouse_in_base_unit_id,
  warehouse_out_unit_id      = EXCLUDED.warehouse_out_unit_id,
  warehouse_out_quantity     = EXCLUDED.warehouse_out_quantity,
  warehouse_out_base_unit_id = EXCLUDED.warehouse_out_base_unit_id,
  updated_at                = NOW();

-- Review any missing erp_inventory_name (should return 0 rows if all matched):
-- SELECT DISTINCT erp_inventory_name
-- FROM joined
-- WHERE erp_inventory_id IS NULL
-- ORDER BY 1;
